### ISSUE TITLE
Error on docker-compose up -d

### ISSUE THREAD

**Issue by phouverneyuff** [dstarcev/parity-poa-playground#1]
I'm getting this error on executing `docker compose up -d`:
`ERROR: repository ethcore/parity not found: does not exist or no pull access`

![image](https://user-images.githubusercontent.com/9394724/27416384-7ba5f0ac-56e3-11e7-853b-ed59e702e3a1.png)

**Comment by dstarcev** [comment]
Hi @phouverneyuff, thanks for reporting this.
The Parity docker image has been renamed from `ethcore/parity` to `parity/parity`, so we just need to rename it accordingly in `docker-compose.yml`

**Comment by dstarcev** [comment]
Fixed
